<?php

namespace App\Support;

/**
 * Server-side twin of frontend/src/lib/levels.js — keep the two in sync.
 * Levels 31-39 are intentionally absent (the table jumps 30 -> 40 to mark
 * the Real Streamer -> Pro Streamer gap). Levels 46+ aren't hand-authored;
 * they're generated by compounding level 45's threshold at a fixed 1.45x
 * step each level, which sits in the requested 1.4-1.5x range and keeps
 * the numbers reproducible.
 */
class StreamerLevels
{
    public const TIER_JUNIOR = 'Junior Streamer';
    public const TIER_REAL = 'Real Streamer';
    public const TIER_PRO = 'Pro Streamer';

    private const PRO_SCALE_STEP = 1.45;

    /** @var array<int, array{level: int, streams: int}> */
    private const BASE_THRESHOLDS = [
        ['level' => 1, 'streams' => 50],
        ['level' => 2, 'streams' => 100],
        ['level' => 3, 'streams' => 200],
        ['level' => 4, 'streams' => 300],
        ['level' => 5, 'streams' => 400],
        ['level' => 6, 'streams' => 500],
        ['level' => 7, 'streams' => 750],
        ['level' => 8, 'streams' => 1_000],
        ['level' => 9, 'streams' => 1_500],
        ['level' => 10, 'streams' => 2_500],
        ['level' => 11, 'streams' => 4_000],
        ['level' => 12, 'streams' => 6_000],
        ['level' => 13, 'streams' => 8_500],
        ['level' => 14, 'streams' => 12_000],
        ['level' => 15, 'streams' => 16_000],
        ['level' => 16, 'streams' => 22_000],
        ['level' => 17, 'streams' => 30_000],
        ['level' => 18, 'streams' => 40_000],
        ['level' => 19, 'streams' => 55_000],
        ['level' => 20, 'streams' => 75_000],
        ['level' => 21, 'streams' => 100_000],
        ['level' => 22, 'streams' => 140_000],
        ['level' => 23, 'streams' => 190_000],
        ['level' => 24, 'streams' => 260_000],
        ['level' => 25, 'streams' => 350_000],
        ['level' => 26, 'streams' => 480_000],
        ['level' => 27, 'streams' => 650_000],
        ['level' => 28, 'streams' => 900_000],
        ['level' => 29, 'streams' => 1_250_000],
        ['level' => 30, 'streams' => 1_800_000],
        ['level' => 40, 'streams' => 3_000_000],
        ['level' => 41, 'streams' => 5_000_000],
        ['level' => 42, 'streams' => 8_000_000],
        ['level' => 43, 'streams' => 12_000_000],
        ['level' => 44, 'streams' => 18_000_000],
        ['level' => 45, 'streams' => 25_000_000],
    ];

    public static function tierForLevel(int $level): string
    {
        if ($level <= 10) {
            return self::TIER_JUNIOR;
        }
        if ($level <= 30) {
            return self::TIER_REAL;
        }

        return self::TIER_PRO;
    }

    /**
     * Threshold table extended (in memory, per call) up to at least
     * $upToLevel.
     *
     * @return array<int, array{level: int, streams: int}>
     */
    private static function extendedThresholds(int $upToLevel): array
    {
        $thresholds = self::BASE_THRESHOLDS;
        $last = end($thresholds);

        $guard = 0;
        while ($last['level'] < $upToLevel && $guard < 2000) {
            $next = [
                'level' => $last['level'] + 1,
                'streams' => (int) round($last['streams'] * self::PRO_SCALE_STEP),
            ];
            $thresholds[] = $next;
            $last = $next;
            $guard++;
        }

        return $thresholds;
    }

    /**
     * Given a user's (or the app's) total stream count for one counter,
     * return the level currently unlocked plus progress toward the next
     * one. Mirrors JS getLevelInfo() exactly.
     *
     * @return array{level:int, tier:string, currentThreshold:int, nextLevel:?int, nextThreshold:?int, progress:float, remaining:int}
     */
    public static function forStreams(int $streams): array
    {
        $streams = max(0, $streams);
        $first = self::BASE_THRESHOLDS[0];

        if ($streams < $first['streams']) {
            return [
                'level' => 0,
                'tier' => self::TIER_JUNIOR,
                'currentThreshold' => 0,
                'nextLevel' => $first['level'],
                'nextThreshold' => $first['streams'],
                'progress' => $streams / $first['streams'],
                'remaining' => $first['streams'] - $streams,
            ];
        }

        $upTo = 50; // enough headroom for essentially all real accounts
        while (true) {
            $thresholds = self::extendedThresholds($upTo);
            $lastStreams = end($thresholds)['streams'];
            if ($streams < $lastStreams || $upTo > 1000) {
                break;
            }
            $upTo += 50;
        }

        for ($i = 0; $i < count($thresholds) - 1; $i++) {
            $current = $thresholds[$i];
            $next = $thresholds[$i + 1];
            if ($streams < $next['streams']) {
                return [
                    'level' => $current['level'],
                    'tier' => self::tierForLevel($current['level']),
                    'currentThreshold' => $current['streams'],
                    'nextLevel' => $next['level'],
                    'nextThreshold' => $next['streams'],
                    'progress' => min(1, max(0, ($streams - $current['streams']) / ($next['streams'] - $current['streams']))),
                    'remaining' => $next['streams'] - $streams,
                ];
            }
        }

        $last = end($thresholds);

        return [
            'level' => $last['level'],
            'tier' => self::tierForLevel($last['level']),
            'currentThreshold' => $last['streams'],
            'nextLevel' => null,
            'nextThreshold' => null,
            'progress' => 1,
            'remaining' => 0,
        ];
    }
}
