// Streamer Level System
// ---------------------------------------------------------------------
// Two independent counters can be leveled: "artist" (a group/member's
// overall play count) and "solo" (a single song / solo-work play count).
// Both use the exact same threshold table.
//
// Levels 31-39 intentionally don't exist — the table jumps 30 -> 40 to
// mark the gap between "Real Streamer" and "Pro Streamer". Levels 46+
// aren't hand-authored; they're generated by compounding the last
// defined threshold (level 45) at a fixed 1.45x step, which sits in the
// middle of the requested 1.4-1.5x range and keeps numbers reproducible
// instead of random.

export const TIERS = {
  JUNIOR: 'Junior Streamer',
  REAL: 'Real Streamer',
  PRO: 'Pro Streamer',
};

export function tierForLevel(level) {
  if (level <= 10) return TIERS.JUNIOR;
  if (level <= 30) return TIERS.REAL;
  return TIERS.PRO;
}

// Hand-authored thresholds, levels 1-45.
const BASE_THRESHOLDS = [
  { level: 1, streams: 50 },
  { level: 2, streams: 100 },
  { level: 3, streams: 200 },
  { level: 4, streams: 300 },
  { level: 5, streams: 400 },
  { level: 6, streams: 500 },
  { level: 7, streams: 750 },
  { level: 8, streams: 1_000 },
  { level: 9, streams: 1_500 },
  { level: 10, streams: 2_500 },
  { level: 11, streams: 4_000 },
  { level: 12, streams: 6_000 },
  { level: 13, streams: 8_500 },
  { level: 14, streams: 12_000 },
  { level: 15, streams: 16_000 },
  { level: 16, streams: 22_000 },
  { level: 17, streams: 30_000 },
  { level: 18, streams: 40_000 },
  { level: 19, streams: 55_000 },
  { level: 20, streams: 75_000 },
  { level: 21, streams: 100_000 },
  { level: 22, streams: 140_000 },
  { level: 23, streams: 190_000 },
  { level: 24, streams: 260_000 },
  { level: 25, streams: 350_000 },
  { level: 26, streams: 480_000 },
  { level: 27, streams: 650_000 },
  { level: 28, streams: 900_000 },
  { level: 29, streams: 1_250_000 },
  { level: 30, streams: 1_800_000 },
  { level: 40, streams: 3_000_000 },
  { level: 41, streams: 5_000_000 },
  { level: 42, streams: 8_000_000 },
  { level: 43, streams: 12_000_000 },
  { level: 44, streams: 18_000_000 },
  { level: 45, streams: 25_000_000 },
];

const PRO_SCALE_STEP = 1.45;

// Cache of generated thresholds beyond level 45, extended lazily as
// higher levels are requested so we're never pre-computing an unbounded
// table up front.
const extendedThresholds = [...BASE_THRESHOLDS];

function ensureThresholdUpTo(level) {
  let last = extendedThresholds[extendedThresholds.length - 1];
  // Safety cap so a corrupt/absurd stream count can never spin this loop
  // forever.
  let guard = 0;
  while (last.level < level && guard < 2000) {
    extendedThresholds.push({
      level: last.level + 1,
      streams: Math.round(last.streams * PRO_SCALE_STEP),
    });
    last = extendedThresholds[extendedThresholds.length - 1];
    guard += 1;
  }
}

export function thresholdForLevel(level) {
  ensureThresholdUpTo(level);
  return extendedThresholds.find((t) => t.level === level) ?? null;
}

/**
 * Given a total stream count, returns the current level info plus what's
 * needed to reach the next one.
 *
 * @param {number} totalStreams
 * @returns {{
 *   level: number,
 *   tier: string,
 *   currentThreshold: number,
 *   nextLevel: number | null,
 *   nextThreshold: number | null,
 *   progress: number,   // 0-1 fraction of the way to nextThreshold
 *   remaining: number,  // streams still needed to hit nextThreshold
 * }}
 */
export function getLevelInfo(totalStreams) {
  const streams = Math.max(0, Number(totalStreams) || 0);

  if (streams < BASE_THRESHOLDS[0].streams) {
    const first = BASE_THRESHOLDS[0];
    return {
      level: 0,
      tier: TIERS.JUNIOR,
      currentThreshold: 0,
      nextLevel: first.level,
      nextThreshold: first.streams,
      progress: streams / first.streams,
      remaining: first.streams - streams,
    };
  }

  // Walk forward, extending the table as needed, until we find the
  // highest level whose threshold the current stream count still clears.
  let i = 0;
  let guard = 0;
  while (guard < 5000) {
    ensureThresholdUpTo(extendedThresholds[extendedThresholds.length - 1].level + 1);
    const current = extendedThresholds[i];
    const next = extendedThresholds[i + 1];
    if (!next || streams < next.streams) {
      const progress = next ? (streams - current.streams) / (next.streams - current.streams) : 1;
      return {
        level: current.level,
        tier: tierForLevel(current.level),
        currentThreshold: current.streams,
        nextLevel: next ? next.level : null,
        nextThreshold: next ? next.streams : null,
        progress: Math.min(1, Math.max(0, progress)),
        remaining: next ? next.streams - streams : 0,
      };
    }
    i += 1;
    guard += 1;
  }
  // Unreachable in practice, but keeps the function total.
  const last = extendedThresholds[extendedThresholds.length - 1];
  return {
    level: last.level,
    tier: tierForLevel(last.level),
    currentThreshold: last.streams,
    nextLevel: null,
    nextThreshold: null,
    progress: 1,
    remaining: 0,
  };
}
